-- Constraints restringe como deve ser o dado a ser gravado
-- UNIQUE, NOT NULL
-- CHECK: só grava o dada se ele obedecer a uma condição (por exemplo, uma coluna de idade impõe que o inteiro deva ser maior que 0)